var server = [
  { server_id: 23, server_name: "[S1] Aurora Point" },
  { server_id: 24, server_name: "[S2] Himeng Valley" },
  { server_id: 25, server_name: "[S3] Kaymo Mountain" },
  { server_id: 26, server_name: "[S4] The Wilterlands" },
  { server_id: 27, server_name: "[S5] Twilight Caverns" },
  { server_id: 28, server_name: "[S6] Windshear Peaks" },
  { server_id: 29, server_name: "[S7] Cragstone" },
  { server_id: 30, server_name: "[S8] Kaspaya Beach" },
  { server_id: 31, server_name: "[S9] Zensho Island" },
  { server_id: 32, server_name: "[S10] Starglade" },
  { server_id: 34, server_name: "[S11] Glimmering Plains" },
  { server_id: 35, server_name: "[S12] Celestial Peaks" },
  { server_id: 36, server_name: "[S13] Blackrock Gorge" },
  { server_id: 37, server_name: "[S14] Lycanmarsh" },
  { server_id: 38, server_name: "[S15] Aquatic Crypts" },
  { server_id: 39, server_name: "[S16] Sea of Dreams" },
  { server_id: 40, server_name: "[S17] Bloodfog Valley" },
  { server_id: 41, server_name: "[S18] Shrine of Kithar" },
  { server_id: 42, server_name: "[S19] Whisperwind Beach" },
  { server_id: 43, server_name: "[S20] Southern Wetlands" },
  { server_id: 44, server_name: "[S21] The Void" },
  { server_id: 45, server_name: "[S22] Tyria Village" },
  { server_id: 46, server_name: "[S23] Angel Island" },
  { server_id: 47, server_name: "[S24] Tundara" },
  { server_id: 48, server_name: "[S25] Falling Stars Bluff" },
  { server_id: 49, server_name: "[S26] Bearpaw Valley" },
  { server_id: 50, server_name: "[S27] Celestial Palace" },
  { server_id: 51, server_name: "[S28] Bloodfang Village" },
  { server_id: 52, server_name: "[S29] The Molten Highlands" },
  { server_id: 53, server_name: "[S30] Altar Of Sacrifice" },
  { server_id: 54, server_name: "[S31] Tree of Life" },
  { server_id: 55, server_name: "[S32] The Necropolis" },
  { server_id: 56, server_name: "[S33] Kraken Beach" },
  { server_id: 58, server_name: "[S34] Void Encampment" },
  { server_id: 59, server_name: "[S35] Sukemo Bluff" },
  { server_id: 60, server_name: "[S36] Mount Nubina" },
  { server_id: 61, server_name: "[S37] Cheurna Gorge" },
  { server_id: 64, server_name: "[S38] Shine of Ariel" },
  { server_id: 66, server_name: "[S39] Erie Marsh" },
  { server_id: 67, server_name: "[S40] Rinulka Peninsula" },
  { server_id: 68, server_name: "[S41] Amethyst Forest" },
  { server_id: 69, server_name: "[S42] Tinosia Delta" },
  { server_id: 71, server_name: "[S43] Killer's  Den" },
  { server_id: 72, server_name: "[S44] Psychodelica" },
  { server_id: 74, server_name: "[S45] Exenden Realm" },
  { server_id: 75, server_name: "[S46] Glacial Planes" },
  { server_id: 76, server_name: "[S47] Sullen Dunes" },
  { server_id: 78, server_name: "[S48] Nebulan Ridge" },
  { server_id: 80, server_name: "[S49] Belas Chasm" },
  { server_id: 81, server_name: "[S50] Crimson Groves" },
  { server_id: 83, server_name: "[S51] Cimmerian Woodlands" },
  { server_id: 85, server_name: "[S52] Plethuran Plains" },
  { server_id: 86, server_name: "[S53] Exelow Hollows" },
  { server_id: 93, server_name: "[S54] Netheran Realm" },
  { server_id: 99, server_name: "[S55] Heavenly Isle" },
  { server_id: 144, server_name: "[S56] Seira Island" },
  { server_id: 162, server_name: "[S57] Eternal Sanctum" },
  { server_id: 202, server_name: "[S58] Holorn Cliff" },
  { server_id: 238, server_name: "[S59] Floran Everglades" },
  { server_id: 274, server_name: "[S60] Exigent Bluff" },
  { server_id: 444, server_name: "[S61] Empyrean Acropolis" },
  { server_id: 533, server_name: "[S62] Bloodshed Hollow" },
  { server_id: 1239, server_name: "[S63] Hellstorm" },
  { server_id: 1693, server_name: "[S64] Purgatory" },
  { server_id: 2233, server_name: "[S65]  Evil Beast Sanctuary" },
  { server_id: 2453, server_name: "[S66] Nightmoor Hollow" },
  { server_id: 2806, server_name: "[S67] Crystal Peak" },
  { server_id: 3174, server_name: "[S68] Silver Hollow" },
  { server_id: 4070, server_name: "[S69] Dark Forest" },
  { server_id: 4402, server_name: "[S70] Silent Sands" },
  { server_id: 4898, server_name: "[S71] Ethereal City" },
  { server_id: 5274, server_name: "[S72]  Moyun Mountain" },
  { server_id: 5734, server_name: "[S73] Green Plains" },
  { server_id: 5894, server_name: "[S74] Bloody Maplewoods" },
  { server_id: 6166, server_name: "[S75] Frozen Wastelands" },
  { server_id: 6294, server_name: "[S76] Karmic Temple" },
  { server_id: 6734, server_name: "[S77] Shadow Moon" },
  { server_id: 7102, server_name: "[S78] Crystal Spire" },
  { server_id: 7302, server_name: "[S79] Shimmering Glade" },
  { server_id: 7498, server_name: "[S80] Guardian's Gate" },
  { server_id: 7830, server_name: "[S81] Vidalian Skyway" },
  { server_id: 8166, server_name: "[S82] Celestial Haven" },
  { server_id: 8446, server_name: "[S83] Crystal Sanctuary" },
  { server_id: 8922, server_name: "[S84] Scion Sanctum" },
  { server_id: 9034, server_name: "[S85] Diaspore" },
  { server_id: 9166, server_name: "[S86] Feldspar" },
  { server_id: 20031, server_name: "[S87] Jargoon" },
  { server_id: 20071, server_name: "[S88] Constance" },
  { server_id: 20098, server_name: "[S89] Archibald" },
  { server_id: 20118, server_name: "[S90] Slippery Slope" },
  { server_id: 20155, server_name: "[S91] Frosty Forest" },
  { server_id: 20186, server_name: "[S92] Brainbash Island" },
  { server_id: 20206, server_name: "[S93] Snow Plains" },
  { server_id: 20232, server_name: "[S94] Wild Autumn" },
  { server_id: 20280, server_name: "[S95] Peach Gardens" },
  { server_id: 20317, server_name: "[S96] Mulberry Village" },
  { server_id: 20354, server_name: "[S97] Silver Ocean" },
  { server_id: 20390, server_name: "[S98] Southern Outpost" },
  { server_id: 20416, server_name: "[S99] Peony Pavilion" },
  { server_id: 20428, server_name: "[S100] Northern Wasteland" },
  { server_id: 20477, server_name: "[S101] Monarch's Rest" },
  { server_id: 20506, server_name: "[S102] Icy Labyrinth" },
  { server_id: 20535, server_name: "[S103] Silent City" },
  { server_id: 20557, server_name: "[S104] Black Heaven" },
  { server_id: 20579, server_name: "[S105] Panglos Hollow" },
  { server_id: 20654, server_name: "[S106] Aphotic Mire" },
  { server_id: 20703, server_name: "[S107] Golden Veil" },
  { server_id: 20718, server_name: "[S108] Emerald Island" },
  { server_id: 20767, server_name: "[S109] Toadmoor Fen" },
  { server_id: 20796, server_name: "[S110] Scarlet Jungle" },
  { server_id: 20803, server_name: "[S111] Desert of Roses" },
  { server_id: 20828, server_name: "[S112] Writhing Swamp" },
  { server_id: 20848, server_name: "[S113] Shimmering Lake" },
  { server_id: 20866, server_name: "[S114] Dreaming Forest" },
  { server_id: 20915, server_name: "[S115] Enchanted Fjord" },
  { server_id: 20929, server_name: "[S116] Windscar Canyons" },
  { server_id: 20941, server_name: "[S117] Shimmering Coast" },
  { server_id: 20970, server_name: "[S118] Fairy Cascades" },
  { server_id: 20986, server_name: "[S119] Glacier Cliffs" },
  { server_id: 20998, server_name: "[S120] Seaside Crevice" },
  { server_id: 21012, server_name: "[S121] Diamond Hills" },
  { server_id: 21017, server_name: "[S122] Rainbow Landing" },
  { server_id: 21034, server_name: "[S123] Coral Strand" },
  { server_id: 21060, server_name: "[S124] Vine Spring" },
  { server_id: 21068, server_name: "[S125] Gamboro Holm" },
  { server_id: 21090, server_name: "[S126] Legrave Stream" },
  { server_id: 21107, server_name: "[S127] Shipheller Grove" },
  { server_id: 21119, server_name: "[S128] Tropic Polde" },
  { server_id: 21122, server_name: "[S129] Forbidden Domain" },
  { server_id: 21142, server_name: "[S130] Wallrood Expanse" },
  { server_id: 21149, server_name: "[S131] Brightjour Thicket" },
  { server_id: 21165, server_name: "[S132] Wallree Pastures" },
  { server_id: 21182, server_name: "[S133] Hinglow Slopes" },
  { server_id: 21227, server_name: "[S134] Creeping Chasm" },
  { server_id: 21261, server_name: "[S135] Burning Peninsula" },
  { server_id: 21294, server_name: "[S136] Haunted Cavern" },
  { server_id: 21331, server_name: "[S137] Snowdown Ridge" },
  { server_id: 21345, server_name: "[S138] Frozen Spring" },
  { server_id: 21380, server_name: "[S139] Crystal Palace" },
  { server_id: 21401, server_name: "[S140] Vale of Calamity" },
  { server_id: 21434, server_name: "[S141] Thundering Butte" },
  { server_id: 21460, server_name: "[S142] Hallowed Fountain" },
  { server_id: 21495, server_name: "[S143] Ghostfade Forest" },
  { server_id: 21536, server_name: "[S144] Mystic Plains" },
  { server_id: 21616, server_name: "[S145] Shadowed Mountain" },
  { server_id: 21654, server_name: "[S146] Ellesmere" },
  { server_id: 21695, server_name: "[S147] Wendlynn" },
  { server_id: 21719, server_name: "[S148] Sacred Forest" },
  { server_id: 21735, server_name: "[S149] Stone Valley" },
  { server_id: 21759, server_name: "[S150] Queens Manor" },
  { server_id: 21784, server_name: "[S151] Shadows Creek" },
  { server_id: 21802, server_name: "[S152] Angels Cove" },
  { server_id: 21838, server_name: "[S153] Canodeen Island" },
  { server_id: 21867, server_name: "[S154] Staggrove" },
  { server_id: 21902, server_name: "[S155] Lagoon Tide" },
  { server_id: 21928, server_name: "[S156] Swandu Creek" },
  { server_id: 21960, server_name: "[S157] Fort Kings" },
  { server_id: 21989, server_name: "[S158] Necromi Graves" },
  { server_id: 22020, server_name: "[S159] Jalapeno" },
  { server_id: 22044, server_name: "[S160] Daemin" },
  { server_id: 22069, server_name: "[S161] Cursed Falls" },
  { server_id: 22097, server_name: "[S162] Red Primroses" },
  { server_id: 22119, server_name: "[S163] Firefly Plains" },
  { server_id: 22141, server_name: "[S164] Deathly Grotto" },
  { server_id: 22164, server_name: "[S165] Silver Valley" },
];

var accounts = [
  {
    account: "arikastevany@google.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "masdasi39@gmail.com",
    password: "maskudasi1",
    server_number: "81",
    server_id: 7830,
  },
  {
    account: "ariebimo@rocketmail.com",
    password: "Bim260698",
    server_number: "73",
    server_id: 5734,
  },
  {
    account: "shooter91",
    password: "12345",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "kingace_27",
    password: "rincoreiys123",
    server_number: "85",
    server_id: 9034,
  },
  {
    account: "gallagherdic@aol.com",
    password: "27944524",
    server_number: "101",
    server_id: 20477,
  },
  {
    account: "pamungkasa33@yahoo.co.id",
    password: "rincoreiys123",
    server_number: "60",
    server_id: 274,
  },
  {
    account: "bodonk@mutiaraflorist.com",
    password: "161090devilz",
    server_number: "73",
    server_id: 5734,
  },
  {
    account: "kucing16@gmail.com",
    password: "161090devilz",
    server_number: "120",
    server_id: 20998,
  },
  { account: "gheiza", password: "ariek", server_number: "27", server_id: 50 },
  {
    account: "ariebimo@ymail.com",
    password: "bim12345",
    server_number: "73",
    server_id: 5734,
  },
  {
    account: "wildthang2324@gmail.com",
    password: "27944524",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "febri7299@gmail.com",
    password: "7021999",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "sifuenteszywan@hotmail.com",
    password: "AdolescenT3",
    server_number: "85",
    server_id: 9034,
  },
  {
    account: "bespavxzjodah@hotmail.com",
    password: "sECoNdO43769",
    server_number: "99",
    server_id: 20416,
  },
  {
    account: "yballekgvxbo@hotmail.com",
    password: "aLimoNY236",
    server_number: "99",
    server_id: 20416,
  },
  {
    account: "patmoreewpno@hotmail.com",
    password: "mACAylE8461",
    server_number: "99",
    server_id: 20416,
  },
  {
    account: "bunkhousesept",
    password: "hippogrIFf9",
    server_number: "85",
    server_id: 9034,
  },
  {
    account: "worthilynouqx",
    password: "pedestriAN7",
    server_number: "85",
    server_id: 9034,
  },
  {
    account: "arika02@gmail.com",
    password: "7Feb1999!",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "arika03@gmail.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "arika04@gmail.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "arika06@gmail.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "arika07@gmail.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "arika08@gmail.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "arika09@gmail.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "arika10@gmail.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "arika11@gmail.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "arika12@gmail.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "arika13@gmail.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "arika14@gmail.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "arika15@gmail.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "arika16@gmail.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "rossijade4@gmail.com",
    password: "jaross24",
    server_number: "87",
    server_id: 20031,
  },
  {
    account: "rincojerard@google.com",
    password: "rincoreiys123",
    server_number: "87",
    server_id: 20031,
  },
];

var modes = {
  "low": {
    description: "<b>Low</b> favors playback speed over appearance.",
    text: "Low (Best performance)"
  },
  "autolow": {
    description: "<b>Autolow</b> emphasizes speed at first but improves appearance whenever possible.",
    text: "AutoLow"
  },
  "autohigh": {
    description: "<b>Autohigh</b> emphasizes playback speed and appearance equally at first but sacrifices appearance for playback speed if necessary.",
    text: "AutoHigh"
  },
  "medium": {
    description: "<b>Autohigh</b> emphasizes playback speed and appearance equally at first but sacrifices appearance for playback speed if necessary.",
    text: "Medium"
  },
  "high": {
    description: "<b>High</b> favors appearance over playback speed.",
    text: "High (Default)"
  },
  "best": {
    description: "<b>Best</b> provides the best display quality and does not consider playback speed.",
    text: "Best (Slow performance, best graphics)"
  }
};
